version: '3.8'
services:
    i-vpp-upf:
        image: rohankharade/oai-upf-vpp:no_gtp_ext
        privileged: true
        container_name: "I-UPF"
        environment:
            - NWI_N3=access.oai.org
            - NWI_N6=core.oai.org
            - GW_ID=1
            - MNC03=95
            - MCC=208
            - REALM=3gppnetwork.org
            - NETWORK_UE_IP=10.10.10.0/24
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - INTERFACE_ACCESS=eth1
            - INTERFACE_CORE=eth2
            - INTERFACE_CP=eth0
            - NSSAI_SD_0=123
            - SST=222
            - DNN=default
            - REGISTER_NRF=no
            - NRF_IP_ADDR=192.168.70.130
            - NRF_PORT=9090
            - HTTP_VERSION=2
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.134
            public_net_access:
                ipv4_address: 192.168.72.134
            public_net_core:
                ipv4_address: 192.168.73.134
    a-vpp-upf:
        image: rohankharade/oai-upf-vpp:no_gtp_ext
        privileged: true
        container_name: "A-UPF"
        environment:
            - NWI_N3=access.oai.org
            - NWI_N6=core.oai.org
            - GW_ID=1
            - MNC03=95
            - MCC=208
            - REALM=3gppnetwork.org
            - NETWORK_UE_IP=20.10.10.0/24
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - INTERFACE_ACCESS=eth1
            - INTERFACE_CORE=eth2
            - INTERFACE_CP=eth0
            - NSSAI_SD_0=123
            - SST=222
            - DNN=default
            - REGISTER_NRF=no
            - N3_IPV4_ADDRESS_LOCAL=192.168.73.203
            - N3_IPV4_ADDRESS_REMOTE=192.168.73.202
            - N4_IPV4_ADDRESS_LOCAL=192.168.80.202
            - N6_IPV4_ADDRESS_LOCAL=192.168.74.203
            - NRF_IP_ADDR=192.168.70.130
            - NRF_PORT=9090
            - HTTP_VERSION=2
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_sec:
                ipv4_address: 192.168.80.135
            public_net_core_sec:
                ipv4_address: 192.168.74.135
            public_net_core:
                ipv4_address: 192.168.73.135
    oai-ext-dn:
        image: ubuntu:bionic
        privileged: true
        container_name: "oai-ext-dn"
        entrypoint: /bin/bash -c \
              "apt update; apt install -y iptables iproute2 iperf3 iputils-ping;"\
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 10.10.10.0/24 via 192.168.74.203 dev eth0; sleep infinity"
        command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
        networks:
            public_net_core_sec:
                ipv4_address: 192.168.74.140
networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.0/24
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    public_net_sec:
        driver: bridge
        name: demo-oai-public-net-sec
        ipam:
            config:
                - subnet: 192.168.80.0/24
        driver_opts:
            com.docker.network.bridge.name: "demo-oai-sec"
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-access"
    public_net_core:
        name: oai-public-core
        ipam:
            config:
                - subnet: 192.168.73.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core"
    public_net_core_sec:
        name: oai-public-core-sec
        ipam:
            config:
                - subnet: 192.168.74.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core-sec"

