messages:
  - messageType: SessionEstablishmentRequest
    messageParams:
      seid: 0
      pdrs:
      - pdrID: 0
        precedence: 0
        pdi:
          sourceInterface: Access
          networkInstance: access.oai.org
          ueIPAddress:
            isDestination: false
            ip4: 10.10.10.10
        outerHeaderRemoval: OUTER_HEADER_GTPU_UDP_IPV4
        farID: 12
      fars:
      - farID: 12
        applyAction: Forward
        forwardingParameters:
          destinationInterface: Core
          networkInstance: core.oai.org
          outerHeaderCreation:
            desc: OUTER_HEADER_CREATION_GTPU_UDP_IPV4
            teid: 4321
            ip: 192.168.72.202

